/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockVerifier, MockVerifierInterface } from "../../Mocks.sol/MockVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      },
      {
        "internalType": "uint256[6]",
        "name": "",
        "type": "uint256[6]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b506101058061001d5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c8063695ef6f914602a575b5f80fd5b603e60353660046052565b60019392505050565b604051901515815260200160405180910390f35b5f805f60e084860312156063575f80fd5b833567ffffffffffffffff808211156079575f80fd5b818601915086601f830112608b575f80fd5b8135818111156098575f80fd5b87602082850101111560a8575f80fd5b6020830195508094505050508460e08501111560c2575f80fd5b602084019050925092509256fea264697066735822122055b0a7980231d2e497aa8ad5761b254e974d2e959c9ebe05cb8980bcd18cdbd764736f6c63430008180033";

  
      type MockVerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockVerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockVerifier__factory extends ContractFactory {
    
      constructor(...args: MockVerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockVerifier__factory {
      return super.connect(runner) as MockVerifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockVerifierInterface {
      return new Interface(_abi) as MockVerifierInterface;
    }
    
    override attach(address: string | Addressable): MockVerifier {
      return super.attach(address) as MockVerifier;
    }
  static connect(address: string, runner?: ContractRunner | null): MockVerifier {
      return new Contract(address, _abi, runner) as unknown as MockVerifier;
    }
  }

  
  