/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockIncrementalMerkleTree, MockIncrementalMerkleTreeInterface } from "../../Mocks.sol/MockIncrementalMerkleTree.js";

  const _abi = [
  {
    "inputs": [],
    "name": "currentRoot",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "insert",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "isKnownRoot",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "nextIndex",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b506101a88061001d5f395ff3fe608060405234801561000f575f80fd5b506004361061004a575f3560e01c80632d287e431461004e5780636d9833e31461007b578063fc7e9c6f1461009f578063fdab463d146100ae575b5f80fd5b61006161005c36600461012b565b6100f8565b60405163ffffffff90911681526020015b60405180910390f35b61008f61008936600461012b565b50600190565b6040519015158152602001610072565b5f546100619063ffffffff1681565b6100ea5f805460405160e09190911b6001600160e01b031916602082015260240160405160208183030381529060405280519060200120905090565b604051908152602001610072565b5f805463ffffffff1661010c816001610142565b5f805463ffffffff191663ffffffff9290921691909117905592915050565b5f6020828403121561013b575f80fd5b5035919050565b63ffffffff81811683821601908082111561016b57634e487b7160e01b5f52601160045260245ffd5b509291505056fea2646970667358221220db6b83ac6cdaf79694da45212e8ed86a32eff3cba69bd62c378b7a47d704ef2364736f6c63430008180033";

  
      type MockIncrementalMerkleTreeConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockIncrementalMerkleTreeConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockIncrementalMerkleTree__factory extends ContractFactory {
    
      constructor(...args: MockIncrementalMerkleTreeConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockIncrementalMerkleTree & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockIncrementalMerkleTree__factory {
      return super.connect(runner) as MockIncrementalMerkleTree__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockIncrementalMerkleTreeInterface {
      return new Interface(_abi) as MockIncrementalMerkleTreeInterface;
    }
    
    override attach(address: string | Addressable): MockIncrementalMerkleTree {
      return super.attach(address) as MockIncrementalMerkleTree;
    }
  static connect(address: string, runner?: ContractRunner | null): MockIncrementalMerkleTree {
      return new Contract(address, _abi, runner) as unknown as MockIncrementalMerkleTree;
    }
  }

  
  