/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface Groth16VerifierAdapterInterface extends Interface {
    getFunction(nameOrSignature: "groth16" | "verifyProof"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'groth16', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyProof', values: [BytesLike, BigNumberish[]]): string;

    decodeFunctionResult(functionFragment: 'groth16', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyProof', data: BytesLike): Result;
  }

  

  export interface Groth16VerifierAdapter extends BaseContract {
    
    connect(runner?: ContractRunner | null): Groth16VerifierAdapter;
    waitForDeployment(): Promise<this>;

    interface: Groth16VerifierAdapterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    groth16: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifyProof: TypedContractMethod<
      [proof: BytesLike, publicInputs: BigNumberish[], ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'groth16'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifyProof'): TypedContractMethod<
      [proof: BytesLike, publicInputs: BigNumberish[], ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }