/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Groth16VerifierAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Groth16VerifierAdapter__factory>
getContractFactory(name: 'Groth16Verifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Groth16Verifier__factory>
getContractFactory(name: 'MockUSDT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDT__factory>
getContractFactory(name: 'MockIncrementalMerkleTree', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockIncrementalMerkleTree__factory>
getContractFactory(name: 'MockVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockVerifier__factory>
getContractFactory(name: 'IIncrementalMerkleTree', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IIncrementalMerkleTree__factory>
getContractFactory(name: 'ISanctionsList', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISanctionsList__factory>
getContractFactory(name: 'IVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IVerifier__factory>
getContractFactory(name: 'TelegramPrivacyPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TelegramPrivacyPool__factory>

  getContractAt(name: 'Groth16VerifierAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Groth16VerifierAdapter>
getContractAt(name: 'Groth16Verifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Groth16Verifier>
getContractAt(name: 'MockUSDT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDT>
getContractAt(name: 'MockIncrementalMerkleTree', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockIncrementalMerkleTree>
getContractAt(name: 'MockVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockVerifier>
getContractAt(name: 'IIncrementalMerkleTree', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IIncrementalMerkleTree>
getContractAt(name: 'ISanctionsList', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISanctionsList>
getContractAt(name: 'IVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IVerifier>
getContractAt(name: 'TelegramPrivacyPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TelegramPrivacyPool>

  deployContract(name: 'Groth16VerifierAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Groth16VerifierAdapter>
deployContract(name: 'Groth16Verifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Groth16Verifier>
deployContract(name: 'MockUSDT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDT>
deployContract(name: 'MockIncrementalMerkleTree', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockIncrementalMerkleTree>
deployContract(name: 'MockVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockVerifier>
deployContract(name: 'IIncrementalMerkleTree', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IIncrementalMerkleTree>
deployContract(name: 'ISanctionsList', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISanctionsList>
deployContract(name: 'IVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IVerifier>
deployContract(name: 'TelegramPrivacyPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TelegramPrivacyPool>

  deployContract(name: 'Groth16VerifierAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Groth16VerifierAdapter>
deployContract(name: 'Groth16Verifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Groth16Verifier>
deployContract(name: 'MockUSDT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDT>
deployContract(name: 'MockIncrementalMerkleTree', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockIncrementalMerkleTree>
deployContract(name: 'MockVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockVerifier>
deployContract(name: 'IIncrementalMerkleTree', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IIncrementalMerkleTree>
deployContract(name: 'ISanctionsList', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISanctionsList>
deployContract(name: 'IVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IVerifier>
deployContract(name: 'TelegramPrivacyPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TelegramPrivacyPool>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  