/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TelegramPrivacyPoolInterface extends Interface {
    getFunction(nameOrSignature: "DENOMINATION" | "commitments" | "deposit" | "nullifierHashes" | "verifier" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposit" | "Withdrawal"): EventFragment;

    encodeFunctionData(functionFragment: 'DENOMINATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'commitments', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'nullifierHashes', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BytesLike, BytesLike, BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DENOMINATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nullifierHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DepositEvent {
      export type InputTuple = [commitment: BytesLike, leafIndex: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [commitment: string, leafIndex: bigint, timestamp: bigint];
      export interface OutputObject {commitment: string, leafIndex: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalEvent {
      export type InputTuple = [to: AddressLike, nullifierHash: BytesLike, relayer: AddressLike, fee: BigNumberish];
      export type OutputTuple = [to: string, nullifierHash: string, relayer: string, fee: bigint];
      export interface OutputObject {to: string, nullifierHash: string, relayer: string, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TelegramPrivacyPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): TelegramPrivacyPool;
    waitForDeployment(): Promise<this>;

    interface: TelegramPrivacyPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DENOMINATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    commitments: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [_commitment: BytesLike, ],
      [void],
      'payable'
    >
    

    
    nullifierHashes: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [_proof: BytesLike, _root: BytesLike, _nullifierHash: BytesLike, _recipient: AddressLike, _relayer: AddressLike, _fee: BigNumberish, _refund: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DENOMINATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'commitments'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [_commitment: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'nullifierHashes'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [_proof: BytesLike, _root: BytesLike, _nullifierHash: BytesLike, _recipient: AddressLike, _relayer: AddressLike, _fee: BigNumberish, _refund: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'Withdrawal'): TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;

    filters: {
      
      'Deposit(bytes32,uint32,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'Withdrawal(address,bytes32,address,uint256)': TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
      Withdrawal: TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
    
    };
  }