/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IIncrementalMerkleTreeInterface extends Interface {
    getFunction(nameOrSignature: "currentRoot" | "insert" | "isKnownRoot"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'currentRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'insert', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isKnownRoot', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'currentRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'insert', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isKnownRoot', data: BytesLike): Result;
  }

  

  export interface IIncrementalMerkleTree extends BaseContract {
    
    connect(runner?: ContractRunner | null): IIncrementalMerkleTree;
    waitForDeployment(): Promise<this>;

    interface: IIncrementalMerkleTreeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    currentRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    insert: TypedContractMethod<
      [leaf: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    isKnownRoot: TypedContractMethod<
      [root: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'currentRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'insert'): TypedContractMethod<
      [leaf: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isKnownRoot'): TypedContractMethod<
      [root: BytesLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }