/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TelegramPrivacyPoolInterface extends Interface {
    getFunction(nameOrSignature: "ASP_ROLE" | "ASP_ROOT_HISTORY" | "COMPLIANCE_ROLE" | "DEFAULT_ADMIN_ROLE" | "ETH_DENOMINATION" | "PAUSER_ROLE" | "PROTOCOL_WITHDRAW_FEE_ETH" | "PROTOCOL_WITHDRAW_FEE_USDT" | "SNARK_SCALAR_FIELD" | "USDT_DENOMINATION" | "accumulatedProtocolFeesEth" | "accumulatedProtocolFeesUsdt" | "addSanctioned" | "aspRootIndex" | "aspRoots" | "deposit" | "depositAmountRequired" | "depositUsdt" | "ethCommitments" | "ethNullifierHashes" | "ethStateTree" | "getRoleAdmin" | "grantRole" | "hasRole" | "isKnownAspRoot" | "isSanctioned" | "knownAspRoot" | "localSanctionedAt" | "localSanctionedLength" | "owner" | "pause" | "paused" | "publishAspRoot" | "removeSanctioned" | "renounceOwnership" | "renounceRole" | "revokeRole" | "sanctionsOracle" | "supportsInterface" | "transferOwnership" | "unpause" | "usdt" | "usdtCommitments" | "usdtDepositAmountRequired" | "usdtNullifierHashes" | "usdtStateTree" | "verifier" | "withdraw" | "withdrawFees" | "withdrawUsdt"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AspRootUpdated" | "DepositEth" | "DepositUsdt" | "OwnershipTransferred" | "Paused" | "ProtocolFeesWithdrawn" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "SanctionedAddressAdded" | "SanctionedAddressRemoved" | "Unpaused" | "WithdrawalEth" | "WithdrawalUsdt"): EventFragment;

    encodeFunctionData(functionFragment: 'ASP_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ASP_ROOT_HISTORY', values?: undefined): string;
encodeFunctionData(functionFragment: 'COMPLIANCE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ETH_DENOMINATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PROTOCOL_WITHDRAW_FEE_ETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'PROTOCOL_WITHDRAW_FEE_USDT', values?: undefined): string;
encodeFunctionData(functionFragment: 'SNARK_SCALAR_FIELD', values?: undefined): string;
encodeFunctionData(functionFragment: 'USDT_DENOMINATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'accumulatedProtocolFeesEth', values?: undefined): string;
encodeFunctionData(functionFragment: 'accumulatedProtocolFeesUsdt', values?: undefined): string;
encodeFunctionData(functionFragment: 'addSanctioned', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'aspRootIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'aspRoots', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'depositAmountRequired', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositUsdt', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'ethCommitments', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'ethNullifierHashes', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'ethStateTree', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isKnownAspRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isSanctioned', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'knownAspRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'localSanctionedAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'localSanctionedLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'publishAspRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'removeSanctioned', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'sanctionsOracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdt', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdtCommitments', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'usdtDepositAmountRequired', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdtNullifierHashes', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'usdtStateTree', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BytesLike, BytesLike, BytesLike, BytesLike, AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawUsdt', values: [BytesLike, BytesLike, BytesLike, BytesLike, AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ASP_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ASP_ROOT_HISTORY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'COMPLIANCE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ETH_DENOMINATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PROTOCOL_WITHDRAW_FEE_ETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PROTOCOL_WITHDRAW_FEE_USDT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SNARK_SCALAR_FIELD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'USDT_DENOMINATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedProtocolFeesEth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedProtocolFeesUsdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addSanctioned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aspRootIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aspRoots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositAmountRequired', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositUsdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ethCommitments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ethNullifierHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ethStateTree', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isKnownAspRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSanctioned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'knownAspRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'localSanctionedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'localSanctionedLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishAspRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeSanctioned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sanctionsOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdtCommitments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdtDepositAmountRequired', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdtNullifierHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdtStateTree', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawUsdt', data: BytesLike): Result;
  }

  
    export namespace AspRootUpdatedEvent {
      export type InputTuple = [root: BytesLike, index: BigNumberish, asp: AddressLike];
      export type OutputTuple = [root: string, index: bigint, asp: string];
      export interface OutputObject {root: string, index: bigint, asp: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEthEvent {
      export type InputTuple = [commitment: BytesLike, leafIndex: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [commitment: string, leafIndex: bigint, timestamp: bigint];
      export interface OutputObject {commitment: string, leafIndex: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositUsdtEvent {
      export type InputTuple = [commitment: BytesLike, leafIndex: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [commitment: string, leafIndex: bigint, timestamp: bigint];
      export interface OutputObject {commitment: string, leafIndex: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProtocolFeesWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amountEth: BigNumberish, amountUsdt: BigNumberish];
      export type OutputTuple = [to: string, amountEth: bigint, amountUsdt: bigint];
      export interface OutputObject {to: string, amountEth: bigint, amountUsdt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SanctionedAddressAddedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SanctionedAddressRemovedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalEthEvent {
      export type InputTuple = [to: AddressLike, nullifierHash: BytesLike, relayer: AddressLike, relayerFee: BigNumberish, protocolFee: BigNumberish];
      export type OutputTuple = [to: string, nullifierHash: string, relayer: string, relayerFee: bigint, protocolFee: bigint];
      export interface OutputObject {to: string, nullifierHash: string, relayer: string, relayerFee: bigint, protocolFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalUsdtEvent {
      export type InputTuple = [to: AddressLike, nullifierHash: BytesLike, relayer: AddressLike, relayerFee: BigNumberish, protocolFee: BigNumberish];
      export type OutputTuple = [to: string, nullifierHash: string, relayer: string, relayerFee: bigint, protocolFee: bigint];
      export interface OutputObject {to: string, nullifierHash: string, relayer: string, relayerFee: bigint, protocolFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TelegramPrivacyPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): TelegramPrivacyPool;
    waitForDeployment(): Promise<this>;

    interface: TelegramPrivacyPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ASP_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ASP_ROOT_HISTORY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    COMPLIANCE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ETH_DENOMINATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PROTOCOL_WITHDRAW_FEE_ETH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PROTOCOL_WITHDRAW_FEE_USDT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SNARK_SCALAR_FIELD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    USDT_DENOMINATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    accumulatedProtocolFeesEth: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    accumulatedProtocolFeesUsdt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addSanctioned: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    aspRootIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    aspRoots: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [commitment: BytesLike, ],
      [void],
      'payable'
    >
    

    
    depositAmountRequired: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    depositUsdt: TypedContractMethod<
      [commitment: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    ethCommitments: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    ethNullifierHashes: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    ethStateTree: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isKnownAspRoot: TypedContractMethod<
      [root: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    isSanctioned: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    knownAspRoot: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    localSanctionedAt: TypedContractMethod<
      [i: BigNumberish, ],
      [string],
      'view'
    >
    

    
    localSanctionedLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    publishAspRoot: TypedContractMethod<
      [newRoot: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeSanctioned: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    sanctionsOracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    usdt: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdtCommitments: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    usdtDepositAmountRequired: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdtNullifierHashes: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    usdtStateTree: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [proof: BytesLike, stateRoot: BytesLike, aspRoot: BytesLike, nullifierHash: BytesLike, recipient: AddressLike, relayer: AddressLike, fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawUsdt: TypedContractMethod<
      [proof: BytesLike, stateRoot: BytesLike, aspRoot: BytesLike, nullifierHash: BytesLike, recipient: AddressLike, relayer: AddressLike, fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ASP_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ASP_ROOT_HISTORY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'COMPLIANCE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ETH_DENOMINATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PROTOCOL_WITHDRAW_FEE_ETH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PROTOCOL_WITHDRAW_FEE_USDT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SNARK_SCALAR_FIELD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'USDT_DENOMINATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'accumulatedProtocolFeesEth'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'accumulatedProtocolFeesUsdt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addSanctioned'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'aspRootIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'aspRoots'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [commitment: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'depositAmountRequired'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'depositUsdt'): TypedContractMethod<
      [commitment: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ethCommitments'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'ethNullifierHashes'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'ethStateTree'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isKnownAspRoot'): TypedContractMethod<
      [root: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isSanctioned'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'knownAspRoot'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'localSanctionedAt'): TypedContractMethod<
      [i: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'localSanctionedLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'publishAspRoot'): TypedContractMethod<
      [newRoot: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeSanctioned'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sanctionsOracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdt'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdtCommitments'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'usdtDepositAmountRequired'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdtNullifierHashes'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'usdtStateTree'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [proof: BytesLike, stateRoot: BytesLike, aspRoot: BytesLike, nullifierHash: BytesLike, recipient: AddressLike, relayer: AddressLike, fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawUsdt'): TypedContractMethod<
      [proof: BytesLike, stateRoot: BytesLike, aspRoot: BytesLike, nullifierHash: BytesLike, recipient: AddressLike, relayer: AddressLike, fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AspRootUpdated'): TypedContractEvent<AspRootUpdatedEvent.InputTuple, AspRootUpdatedEvent.OutputTuple, AspRootUpdatedEvent.OutputObject>;
getEvent(key: 'DepositEth'): TypedContractEvent<DepositEthEvent.InputTuple, DepositEthEvent.OutputTuple, DepositEthEvent.OutputObject>;
getEvent(key: 'DepositUsdt'): TypedContractEvent<DepositUsdtEvent.InputTuple, DepositUsdtEvent.OutputTuple, DepositUsdtEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'ProtocolFeesWithdrawn'): TypedContractEvent<ProtocolFeesWithdrawnEvent.InputTuple, ProtocolFeesWithdrawnEvent.OutputTuple, ProtocolFeesWithdrawnEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'SanctionedAddressAdded'): TypedContractEvent<SanctionedAddressAddedEvent.InputTuple, SanctionedAddressAddedEvent.OutputTuple, SanctionedAddressAddedEvent.OutputObject>;
getEvent(key: 'SanctionedAddressRemoved'): TypedContractEvent<SanctionedAddressRemovedEvent.InputTuple, SanctionedAddressRemovedEvent.OutputTuple, SanctionedAddressRemovedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'WithdrawalEth'): TypedContractEvent<WithdrawalEthEvent.InputTuple, WithdrawalEthEvent.OutputTuple, WithdrawalEthEvent.OutputObject>;
getEvent(key: 'WithdrawalUsdt'): TypedContractEvent<WithdrawalUsdtEvent.InputTuple, WithdrawalUsdtEvent.OutputTuple, WithdrawalUsdtEvent.OutputObject>;

    filters: {
      
      'AspRootUpdated(bytes32,uint32,address)': TypedContractEvent<AspRootUpdatedEvent.InputTuple, AspRootUpdatedEvent.OutputTuple, AspRootUpdatedEvent.OutputObject>;
      AspRootUpdated: TypedContractEvent<AspRootUpdatedEvent.InputTuple, AspRootUpdatedEvent.OutputTuple, AspRootUpdatedEvent.OutputObject>;
    

      'DepositEth(bytes32,uint32,uint256)': TypedContractEvent<DepositEthEvent.InputTuple, DepositEthEvent.OutputTuple, DepositEthEvent.OutputObject>;
      DepositEth: TypedContractEvent<DepositEthEvent.InputTuple, DepositEthEvent.OutputTuple, DepositEthEvent.OutputObject>;
    

      'DepositUsdt(bytes32,uint32,uint256)': TypedContractEvent<DepositUsdtEvent.InputTuple, DepositUsdtEvent.OutputTuple, DepositUsdtEvent.OutputObject>;
      DepositUsdt: TypedContractEvent<DepositUsdtEvent.InputTuple, DepositUsdtEvent.OutputTuple, DepositUsdtEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'ProtocolFeesWithdrawn(address,uint256,uint256)': TypedContractEvent<ProtocolFeesWithdrawnEvent.InputTuple, ProtocolFeesWithdrawnEvent.OutputTuple, ProtocolFeesWithdrawnEvent.OutputObject>;
      ProtocolFeesWithdrawn: TypedContractEvent<ProtocolFeesWithdrawnEvent.InputTuple, ProtocolFeesWithdrawnEvent.OutputTuple, ProtocolFeesWithdrawnEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'SanctionedAddressAdded(address)': TypedContractEvent<SanctionedAddressAddedEvent.InputTuple, SanctionedAddressAddedEvent.OutputTuple, SanctionedAddressAddedEvent.OutputObject>;
      SanctionedAddressAdded: TypedContractEvent<SanctionedAddressAddedEvent.InputTuple, SanctionedAddressAddedEvent.OutputTuple, SanctionedAddressAddedEvent.OutputObject>;
    

      'SanctionedAddressRemoved(address)': TypedContractEvent<SanctionedAddressRemovedEvent.InputTuple, SanctionedAddressRemovedEvent.OutputTuple, SanctionedAddressRemovedEvent.OutputObject>;
      SanctionedAddressRemoved: TypedContractEvent<SanctionedAddressRemovedEvent.InputTuple, SanctionedAddressRemovedEvent.OutputTuple, SanctionedAddressRemovedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'WithdrawalEth(address,bytes32,address,uint256,uint256)': TypedContractEvent<WithdrawalEthEvent.InputTuple, WithdrawalEthEvent.OutputTuple, WithdrawalEthEvent.OutputObject>;
      WithdrawalEth: TypedContractEvent<WithdrawalEthEvent.InputTuple, WithdrawalEthEvent.OutputTuple, WithdrawalEthEvent.OutputObject>;
    

      'WithdrawalUsdt(address,bytes32,address,uint256,uint256)': TypedContractEvent<WithdrawalUsdtEvent.InputTuple, WithdrawalUsdtEvent.OutputTuple, WithdrawalUsdtEvent.OutputObject>;
      WithdrawalUsdt: TypedContractEvent<WithdrawalUsdtEvent.InputTuple, WithdrawalUsdtEvent.OutputTuple, WithdrawalUsdtEvent.OutputObject>;
    
    };
  }