/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IIncrementalMerkleTree, IIncrementalMerkleTreeInterface } from "../../PrivacyPool.sol/IIncrementalMerkleTree.js";

  const _abi = [
  {
    "inputs": [],
    "name": "currentRoot",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "leaf",
        "type": "bytes32"
      }
    ],
    "name": "insert",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "leafIndex",
        "type": "uint32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "root",
        "type": "bytes32"
      }
    ],
    "name": "isKnownRoot",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IIncrementalMerkleTree__factory {
    static readonly abi = _abi;
    static createInterface(): IIncrementalMerkleTreeInterface {
      return new Interface(_abi) as IIncrementalMerkleTreeInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IIncrementalMerkleTree {
      return new Contract(address, _abi, runner) as unknown as IIncrementalMerkleTree;
    }
  }
  