/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ISanctionsList, ISanctionsListInterface } from "../../PrivacyPool.sol/ISanctionsList.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "addr",
        "type": "address"
      }
    ],
    "name": "isSanctioned",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ISanctionsList__factory {
    static readonly abi = _abi;
    static createInterface(): ISanctionsListInterface {
      return new Interface(_abi) as ISanctionsListInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ISanctionsList {
      return new Contract(address, _abi, runner) as unknown as ISanctionsList;
    }
  }
  